"""initial schema

Revision ID: 079de84e4f44
Revises:
Create Date: 2026-07-24 10:05:38.106833
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "079de84e4f44"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_subject", sa.String(length=255), nullable=True),
        sa.Column("target_id", sa.String(length=255), nullable=True),
        sa.Column("recipient_subject", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.String(length=128), nullable=True),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_action", "audit_records", ["action", "occurred_at"], unique=False)
    op.create_index(
        "ix_audit_actor", "audit_records", ["actor_subject", "occurred_at"], unique=False
    )
    op.create_index("ix_audit_occurred_at", "audit_records", ["occurred_at"], unique=False)
    op.create_index("ix_audit_target", "audit_records", ["target_id", "occurred_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("root_folder_id", sa.UUID(), nullable=False),
        sa.Column("quota_bytes", sa.BigInteger(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("org", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("orgs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_subject"), "users", ["subject"], unique=True)
    op.create_table(
        "nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("encrypted", sa.Boolean(), nullable=False),
        sa.Column("encryption_default", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_nodes_deleted_at",
        "nodes",
        ["deleted_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NOT NULL"),
    )
    op.create_index("ix_nodes_owner", "nodes", ["owner_id"], unique=False)
    op.create_index("ix_nodes_owner_name", "nodes", ["owner_id", "normalized_name"], unique=False)
    op.create_index(
        "ix_nodes_parent_live",
        "nodes",
        ["parent_id", "normalized_name"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_nodes_parent_name_live",
        "nodes",
        ["parent_id", "normalized_name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "quota_usage",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("live_bytes", sa.BigInteger(), nullable=False),
        sa.Column("trashed_bytes", sa.BigInteger(), nullable=False),
        sa.Column("version_bytes", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_keys",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("wrapped_kek", sa.LargeBinary(), nullable=False),
        sa.Column("master_key_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index("ix_user_keys_master", "user_keys", ["master_key_id"], unique=False)
    op.create_table(
        "file_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("plaintext_digest", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("encrypted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_id", "sequence", name="uq_file_versions_node_sequence"),
    )
    op.create_index("ix_file_versions_node", "file_versions", ["node_id", "sequence"], unique=False)
    op.create_table(
        "grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column("granted_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_id", "subject", name="uq_grants_node_subject"),
    )
    op.create_index("ix_grants_node", "grants", ["node_id"], unique=False)
    op.create_index("ix_grants_subject_node", "grants", ["subject", "node_id"], unique=False)
    op.create_table(
        "public_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("passphrase_hash", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_public_links_active",
        "public_links",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index("ix_public_links_node", "public_links", ["node_id"], unique=False)
    op.create_index(op.f("ix_public_links_token_hash"), "public_links", ["token_hash"], unique=True)
    op.create_table(
        "wrapped_data_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("wrapped_dek", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_id", "subject", name="uq_wrapped_data_keys_node_subject"),
    )
    op.create_index("ix_wrapped_data_keys_node", "wrapped_data_keys", ["node_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wrapped_data_keys_node", table_name="wrapped_data_keys")
    op.drop_table("wrapped_data_keys")
    op.drop_index(op.f("ix_public_links_token_hash"), table_name="public_links")
    op.drop_index("ix_public_links_node", table_name="public_links")
    op.drop_index(
        "ix_public_links_active",
        table_name="public_links",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("public_links")
    op.drop_index("ix_grants_subject_node", table_name="grants")
    op.drop_index("ix_grants_node", table_name="grants")
    op.drop_table("grants")
    op.drop_index("ix_file_versions_node", table_name="file_versions")
    op.drop_table("file_versions")
    op.drop_index("ix_user_keys_master", table_name="user_keys")
    op.drop_table("user_keys")
    op.drop_table("quota_usage")
    op.drop_index(
        "uq_nodes_parent_name_live",
        table_name="nodes",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_nodes_parent_live", table_name="nodes", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index("ix_nodes_owner_name", table_name="nodes")
    op.drop_index("ix_nodes_owner", table_name="nodes")
    op.drop_index(
        "ix_nodes_deleted_at",
        table_name="nodes",
        postgresql_where=sa.text("deleted_at IS NOT NULL"),
    )
    op.drop_table("nodes")
    op.drop_index(op.f("ix_users_subject"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_audit_target", table_name="audit_records")
    op.drop_index("ix_audit_occurred_at", table_name="audit_records")
    op.drop_index("ix_audit_actor", table_name="audit_records")
    op.drop_index("ix_audit_action", table_name="audit_records")
    op.drop_table("audit_records")
    # ### end Alembic commands ###
